# Generated by Django 3.0 on 2019-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
